version: '3.8'

services:
  backend:
    build:
      context: .             # Contexto é a RAIZ do projeto
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"          # O Nginx da OCI faz proxy para esta porta
    volumes:
      - backend_data:/code/data   # Persistência do banco de dados SQLite e Arquivos

volumes:
  backend_data:
